server:
  port: 8085

spring:
  application:
    name: notification-service

#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: your-email@gmail.com
#    password: your-email-password
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true

kafka:
  bootstrap-servers: localhost:9092
  topics:
    schema-alerts: schema-alert-topic

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
