server:
  port: 8082

spring:
  application:
    name: versioning-service

#  s

kafka:
  bootstrap-servers: localhost:9092
  topics:
    schema-changes: schema-change-topic

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
