apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 80       # The port exposed by the service
      targetPort: 8082  # The port inside the pod
  type: LoadBalancer    # Exposes service to the internet (for AWS, GCP, Azure)
