server:
  port: 8085

spring:
  application:
    name: notification-service



#kafka:
#  bootstrap-servers: localhost:9092
#  topics:
#    schema-alerts: schema-alert-topic

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
