name: CD Pipeline

on:
  workflow_run:
    workflows: ["auth-ci.yml","schema-ci.yml"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set K8s Context
        run: |
          minikube update-context

      - name: Deploy to Minikube
        run: |
          kubectl apply -f k8s/
